blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/macaw-voice/macaw-openvoice/discussions
    about: Please use GitHub Discussions for questions and general support.
